[package]
name = "stellar_lexer"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/quantumatic/stellar"
authors = ["Adi Salimgereyev <adisalimgereev@gmail.com>"]
readme = "../../README.md"
description = "Lexer for the Stellar programming language."

[dependencies]
parking_lot = "0.12.1"
stellar_ast = { path = "../stellar_ast" }
stellar_filesystem = { path = "../stellar_filesystem" }
stellar_interner = { path = "../stellar_interner" }
stellar_stable_likely = { path = "../stellar_stable_likely" }
unicode-xid = "0.2.4"
