[package]
name = "stellar_interner"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/quantumatic/stellar"
authors = ["Adi Salimgereyev <adisalimgereev@gmail.com>"]
readme = "../../README.md"
description = "Implements identifier interner for the Stellar programming language."

[dependencies]
derive_more = "0.99.17"
hashbrown = "0.14.0"
itertools = { version = "0.11.0", optional = true }
serde = { version = "1.0.183", features = ["derive"], optional = true }
stellar_fx_hash = { path = "../stellar_fx_hash" }

[features]
serde = ["dep:serde"]
tuples = ["dep:itertools"]
