[package]
name = "ry_hir"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Adi Salimgereyev <adisalimgereev@gmail.com>"]

[dependencies]
ry_interner = {path = "../ry_interner"}
ry_ast = {path = "../ry_ast"}
ry_span = {path = "../ry_span"}
