[package]
name = "ry_diagnostics"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Adi Salimgereyev <adisalimgereev@gmail.com>"]

[dependencies]
codespan-reporting = "0.11.1"
ry_ast = {path = "../ry_ast"}
