[package]
name = "ry"
version = "0.1.0"
edition = "2021"

[dependencies]
ry_parser = {path = "../ry_parser"}
ry_lexer = {path = "../ry_lexer"}
ry_report = {path = "../ry_report"}
ry_ast = {path = "../ry_ast"}
ry_ast_serializer = {path = "../ry_ast_serializer"}
ry_interner = {path = "../ry_interner"}
codespan-reporting = "0.11.1"
clap = {version = "4.1.4", features = ["derive"]}
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
termcolor = "1.2.0"
